### ISSUE TITLE
Error on run of Qt file.

### ISSUE THREAD

**Issue by robhazes** [angeligareta/SaferAuto#1]
Hei, great project!

I would like to test this project but since I don't have a GPU I did an installation for CPU. Darknet works and OpenCV installed without problems.

I get one error I don't understand when I try to run the SaferAutoGui.pro file within Qt:

/usr/include/opencv/cv.hpp:50:16: fatal error: cv.h: No such file or directory

Seems it can not find the cv.h file, but I checked and both cv.hpp and cv.h are in the usr/include/opencv dir. 

Any idea what is wrong?

Best regards, Rob.

**Comment by angeligareta** [comment]
Apologies for the late response, it might depend on your OpenCV version, check out this [StackOverflow thread](https://stackoverflow.com/questions/10858397/program-cannot-run-opencv-even-though-others-can)
